includes[local] = "/home/vhosts/saurus5_gits/s5_reigo_make/saurus5_core.make"

projects[] = "domain"
projects[] = "facetapi"
projects[job_scheduler][version] = "2.0-alpha2"
projects[ldap][version] = "1.0-beta4"
projects[autosave][version] = "1.x-dev"
projects[] = "migrate"
projects[] = "migrate_extras"
projects[] = "mollom"
projects[] = "search_api"
projects[] = "search_api_attachments"
projects[] = "search_api_solr"

projects[aw_migrate][download][type] = "git"
projects[aw_migrate][download][url] = "https://github.com/kristjanjansen/aw_migrate"
projects[aw_migrate][type] = "module"

libraries[solrphpclient][download][type] = "file"
libraries[solrphpclient][download][url] = "http://solr-php-client.googlecode.com/files/SolrPhpClient.r60.2011-05-04.tgz"
